server:
  port: 8110
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: service-edu
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
  profiles:
    active: dev
  devtools:
    restart:
      poll-interval: 3000ms
      quiet-period:  2999ms
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: info